### ISSUE TITLE
Make intellimouse.py not take over the usb interface on Linux

### ISSUE THREAD

**Issue by madsl** [K-Visscher/pro-intellimouse-control-panel#2] opened 2020-05-20 13:15 UTC
It would be neat if it was possible to use the mouse at the same time as you're setting it up so you can e.g. feel the different DPI settings.

I guess I should try to come up with a patch here myself, but I'll create the issue nevertheless.

**Comment by K-Visscher** [comment] 2020-05-21 05:56
I think that's a great idea! Something like that might be acceptable for a console application, but for a application with a GUI, I agree with you, it's absolutely not. 

I think currently we might already be able to do that, it should be pretty east to implement too. 

Instead of: 
```python
def __init__(self):
	self.reattach = False

	self.device = usb.core.find(idVendor=VID, idProduct=PID)
	if self.device is None:
	    raise ValueError("couldn't find the intellimouse...")

	if sys.platform.startswith("linux"):
		for config in self.device:
			for interface in config:
				if self.device.is_kernel_driver_active(interface.bInterfaceNumber):
					self.device.detach_kernel_driver(interface.bInterfaceNumber)
					self.reattach = True

	self.device.set_configuration()
```

We could probably get away with doing the following:
```python
def __init__(self):
	self.reattach = False

	self.device = usb.core.find(idVendor=VID, idProduct=PID)
	if self.device is None:
	    raise ValueError("couldn't find the intellimouse...")

	if sys.platform.startswith("linux"):
		for config in self.device:
			for interface in config:
				if self.device.is_kernel_driver_active(interface.bInterfaceNumber):
					self.device.detach_kernel_driver(interface.bInterfaceNumber)
					self.reattach = True

	self.device.set_configuration()

        # reattach the the kernel driver responsible for mouse control. 
        self.device.attach_kernel_driver(0)
```

I think this should work because we only need [interface 1](https://i.imgur.com/JlxBh32.png) to be detached (the keyboard interface used for configuring, e.g. setting DPI and such)

If the above doesn't end up work, we could detach and then attach all interfaces before every read/write (this would probably end up being unnoticeable by the end-user, since it happens relatively fast)

The author's of libusb [recommend ](https://github.com/libusb/libusb/wiki/FAQ#does-libusb-support-usb-hid-devices) using HIDAPI for HID interactions, precisely for the reasons we're currently running into. However since the second interface is a keyboard we might still end up not being allowed to do HID interactions with it, since technically you would be able to build a keylogger of some sorts (if it was actually a keyboard 🙄).

**Comment by madsl** [comment] 2020-05-28 07:20
Your fix worked great, by the way! Sorry for being so late with testing, but with that snippet of yours as the new __init__(), you can use and set values in the control panel while still using the mouse :)

A sidenote: Do you think that the dpi setting should reflect mouse and keyboard center so there's 200 dpi between each tick? As the control panel is now, you can set the dpi down to single digit accuracy. Don't know if that's good or bad though...

**Comment by K-Visscher** [comment] 2020-06-28 15:32
Hi @madsl,

Sorry for taking literally a month for getting back to you... (been quite busy with my studies)
This issue should be solved by the closing of issue #5 and the merge of pull request #6, so please let me know if i can close this!

> A sidenote: Do you think that the dpi setting should reflect mouse and keyboard center so there's 200 dpi between each tick?

The Microsoft Mouse and Keyboard Center allows for steps of 50 DPI in the range of 200 to 16000 for the Microsoft Pro IntelliMouse. So I'm not sure where the 200 DPI steps come from? Maybe you're confusing the Pro with the Classic?

> As the control panel is now, you can set the dpi down to single digit accuracy. Don't know if that's good or bad though...

This shouldn't be possible, if you can reliably reproduce this, you can open a issue for it. The slider might give the impression of being able to set the DPI to a single digit, since it has so many different possible values (16000 - 200) / 50 = 316.
But you should still see the line edit being updated properly with step values of 50, if this isn't the case, please open an issue. Also if you were truly able to set it to a single digit, an exception should been thrown when writing the DPI to the device, causing the "something went wrong" screen to be displayed. 
Once again, please open an issue if this is the case.

> Edit: that was wrong - it's more like 50 dpi if i read the code right? Having trouble with selecting 2000 dpi though, I don't quite get it...

Yes, it should be steps of 50. 
If you're having trouble setting the desired DPI using the slider, there's always the line edit, which currently only accepts valid inputs. 
Meaning that at no point the DPI, you're trying to input is allowed to be invalid (this should probably be loosened up, e.g. validate the input once focus is lost or the user presses enter).
This not really a bug as this is expected behaviour, but isn't super user-friendly either, and is a probably good enhancement.

**Comment by madsl** [comment] 2020-07-03 07:42
Nice, thanks for this!

I'm at work now, and here I only have the Classic mouse, and I don't think the rewrite has support for that yet? I can test the Pro IntelliMouse when I get home.

**Comment by madsl** [comment] 2020-07-05 09:41
Hmm, after switching to the cython-hidapi, the code that enumerates the mouse don't quite match what I see on my system, making the control panel not finding the mouse...

Here's my hid.enumerate:
hid.enumerate(0x045E, 0x082A)                                                                                                                                                        
Out[5]: 
[{'path': b'0001:0006:00',
  'vendor_id': 1118,
  'product_id': 2090,
  'serial_number': '',
  'release_number': 149,
  'manufacturer_string': 'Microsoft',
  'product_string': 'Microsoft Pro Intellimouse',
  'usage_page': 0,
  'usage': 0,
  'interface_number': 0},
 {'path': b'0001:0006:01',
  'vendor_id': 1118,
  'product_id': 2090,
  'serial_number': '',
  'release_number': 149,
  'manufacturer_string': 'Microsoft',
  'product_string': 'Microsoft Pro Intellimouse',
  'usage_page': 0,
  'usage': 0,
  'interface_number': 1}]

usage and usage_page with me does not match __USAGE_PAGE = 0xFF07 and __USAGE = 0x212, so it's not found.. Maybe I'm missing something?

**Comment by madsl** [comment] 2020-07-05 09:44
If i just take away usage and usage_page from the statement, the program works again:

`paths = [path for path in hid.enumerate(self.__VID, self.__PID) if path.get("interface_number") == self.__INTERFACE]`

**Closed** 2020-07-07 11:16 UTC
Labels: enhancement
